Repository ISIS3510-202410-Team-13/Analytics, pull requests merged in 2024-03, with the labels that each got.

#7 Add Mockups, Dashboard and generators of BQ 4.1
  README.md
  dashboards/bq4.1.pdf
  excel_mockups/bq4.1.xlsx
  generators/bq4.1.py
Labels: feature

#9 6 create support files and dashboard to answer bq 21
  README.md
  dashboards/bq2.1.pdf
  excel_mockups/bq2.1.xlsx
  generators/bq2.1.py
Labels: feature

#10 BQ 3.4 Analytics
  README.md
  dashboards/bq3.4.pdf
  excel_mockups/bq3.4.xlsx
  generators/bq3.4.py
Labels: feature

#4 3-create-support-files-and-dashboard-to-answer-bq-23
  README.md
  dashboards/BQ2.3.pdf
  excel_mockups/BQ2.3.xlsx
  generators/BQ2.3.py
Labels: feature

#14 Fix language
  dashboards/bq4.1.pdf
Labels: bug

#11 Update README.md
  README.md
Labels: documentation

#15 Add Details to README
  README.md
Labels: documentation

#16 Sprint 2 Release - Analytics
  README.md
  dashboards/BQ2.3.pdf
  dashboards/bq2.1.pdf
  dashboards/bq3.4.pdf
  dashboards/bq4.1.pdf
  dashboards/bq5.2.pdf
  excel_mockups/BQ2.3.xlsx
  excel_mockups/bq2.1.xlsx
  excel_mockups/bq3.4.xlsx
  excel_mockups/bq4.1.xlsx
  excel_mockups/bq5.2.xlsx
  generators/BQ2.3.py
  generators/bq2.1.py
  generators/bq3.4.py
  generators/bq4.1.py
  generators/bq5.2.py
Labels: release
